### ISSUE TITLE
Native Apple Silicon support

### ISSUE THREAD

**Issue by olejnjak** [muxinc/mux-stats-google-ima#12]
Hello, is there any serious reason why, ARM64 simulator is excluded in podspec, especially when other iOS lib by muxinc support it natively?

Thanks

**Comment by olejnjak** [comment]
Seems to work just fine in [my fork](https://github.com/olejnjak/mux-stats-google-ima/tree/master), just updating dependencies and deployment target...

**Comment by nidhik** [comment]
@olejnjak We have released this (for iOS simulators) in [v0.8.0](https://github.com/muxinc/mux-stats-google-ima/releases/tag/v0.8.0). Thank you for your patience!

**Comment by nidhik** [comment]
@olejnjak have you been able to try out v0.8.0? If it is working well, please feel free to close this issue

**Comment by olejnjak** [comment]
Well, not really as I opened this issue to allow our player supplier to avoid excluding arm64 sim. I haven't received their updated library as they are working on it. I will close this issue now and eventually reopen if there are any issues.
