### ISSUE TITLE
0.13.0 isn't released as podspec

### ISSUE THREAD

**Issue by welsinga** [muxinc/mux-stats-google-ima#43]
0.13.0 isn't pushed als podspec. https://github.com/CocoaPods/Specs/tree/master/Specs/f/1/c/Mux-Stats-Google-IMA doesn't contain the new version

**Comment by welsinga** [comment]
@andrewjl-mux did you forget to publish this

**Comment by andrewjl-mux** [comment]
Hey @welsinga, thank you for letting us know. `0.13.0` is now available: https://github.com/CocoaPods/Specs/tree/master/Specs/f/1/c/Mux-Stats-Google-IMA/0.13.0
