### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by ninjazoete** [muxinc/mux-stats-google-ima#5]
Hi, I was able to setup all the MUX libraries for iOS project, but now I need tvOS part of it to be compatible with MUX.

I was able to download and link Core and Stats library against tvOS target but cant  get mux-stats-google-ima to fetch/link on TV.

Is there any way to use it on tvOS project? We use DAI IMA Ads on TV app as well as on iOS.

**Comment by jsanford8** [comment]
Hi @ninjazoete - this does not currently support Google's IMA SDK for tvOS, but we are looking into this this sprint to see if we can add support for it. In the meantime, you should not use this project on your tvOS application.

We will provide updates as we have them on this support.

**Comment by dylanjha** [comment]
Hi @ninjazoete tvOS support has been added in the latest release (0.5.0). Please try that and let me know if you have any issues!
